### ISSUE TITLE
Plugin installation failed with status code 404

### ISSUE THREAD

**Issue by harmenweber** [AntonShuvaev/intellij-dynamodb#12]
Installing the plugin from the plugins marketplace inside IntelliJ IDEA 2022.1.4 (Ultimate Edition) fails. An error popup with the following message is displayed: 

> **Plugin Installation**
Plugin "DynamoDB" was not installed: 
Request failed with status code 404

The following exception gets logged in the log file:

```
2022-07-25 22:50:19,698 [44199438]   INFO - #c.i.o.u.i.PluginDownloader - Request failed with status code 404
com.intellij.util.io.HttpRequests$HttpStatusException: Request failed with status code 404. Status=404, Url=https://plugins.jetbrains.com/pluginManager/?id=org.dynamodb4idea&build=IU-999.SNAPSHOT&uuid=0104222aafebc17-b9fd-49d2-b93c-36778b43835e
	at com.intellij.util.io.HttpRequests.throwHttpStatusError(HttpRequests.java:652)
	at com.intellij.util.io.HttpRequests.openConnection(HttpRequests.java:630)
	at com.intellij.util.io.HttpRequests$RequestImpl.getConnection(HttpRequests.java:359)
	at com.intellij.util.io.HttpRequests$RequestImpl.getInputStream(HttpRequests.java:367)
	at com.intellij.util.io.HttpRequests$RequestImpl.saveToFile(HttpRequests.java:458)
	at com.intellij.util.io.HttpRequests$Request.saveToFile(HttpRequests.java:91)
	at com.intellij.ide.plugins.marketplace.MarketplacePluginDownloadService$downloadPlugin$1.process(MarketplacePluginDownloadService.kt:75)
	at com.intellij.ide.plugins.marketplace.MarketplacePluginDownloadService$downloadPlugin$1.process(MarketplacePluginDownloadService.kt:37)
	at com.intellij.util.io.HttpRequests.doProcess(HttpRequests.java:516)
	at com.intellij.util.io.HttpRequests.process(HttpRequests.java:498)
	at com.intellij.util.io.HttpRequests$RequestBuilderImpl.connect(HttpRequests.java:333)
	at com.intellij.ide.plugins.marketplace.MarketplacePluginDownloadService.downloadPlugin(MarketplacePluginDownloadService.kt:73)
	at com.intellij.openapi.updateSettings.impl.PluginDownloader.tryDownloadPlugin(PluginDownloader.java:358)
	at com.intellij.openapi.updateSettings.impl.PluginDownloader.prepareToInstall(PluginDownloader.java:218)
	at com.intellij.ide.plugins.PluginInstallOperation.prepareToInstall(PluginInstallOperation.java:257)
	at com.intellij.ide.plugins.PluginInstallOperation.prepareToInstallWithCallback(PluginInstallOperation.java:225)
	at com.intellij.ide.plugins.PluginInstallOperation.prepareToInstall(PluginInstallOperation.java:198)
	at com.intellij.ide.plugins.PluginInstallOperation.run(PluginInstallOperation.java:138)
	at com.intellij.ide.plugins.newui.MyPluginModel.runInstallOperation(MyPluginModel.java:441)
	at com.intellij.ide.plugins.newui.MyPluginModel$1.run(MyPluginModel.java:409)
	at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:442)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:114)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsynchronously$5(CoreProgressManager.java:493)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:244)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:189)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:608)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:683)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:639)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:607)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:176)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:244)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

Thanks for help.

**Comment by AntonShuvaev** [comment]
Hi,

Could you try one more time, it looks like Jetbrains server issue. If it doesn't help you can download plugin from https://plugins.jetbrains.com/plugin/18896-dynamodb/versions/stable/193964 and install it manually from disk https://www.jetbrains.com/help/idea/managing-plugins.html#install_plugin_from_disk

**Comment by harmenweber** [comment]
Hi

Just retried two times without success. I still get the same error.

I downloaded the plugin and installed it from disk. Thanks a lot for that hint.

Assuming that it is a Jetbrains server issue, I will close this issue. In case that assumption is wrong and the problem persists, someone else can raise this issue again.

Cheers
